trigger:
  - main
  - refs/tags/*

pr:
  - main
  - main_based_androidx*
  - master_based_androidx*
  
variables:
  BUILD_NUMBER: $(Build.BuildNumber)
  BUILD_COMMIT: $(Build.SourceVersion)
#   XAMARIN_ANDROID_PATH: <path to Xamarin.Android>

resources:
  repositories:
    - repository: internal-templates
      type: github
      name: xamarin/yaml-templates
      endpoint: xamarin
    - repository: components
      type: github
      name: xamarin/XamarinComponents
      endpoint: xamarin

jobs:
  - template: .ci/build.yml@components
    parameters:
      timeoutInMinutes: 240
      areaPath: 'DevDiv\Xamarin SDK\Android'
      preBuildSteps:
        - pwsh: |
            dotnet tool uninstall --global Cake.Tool
            dotnet tool install --global Cake.Tool
            dotnet tool install --global boots
            boots https://public.bl.files.1drv.com/y4m_wkEapXtOn0rKlAzuL8sWhxj2qnTw7iHV2sFqg1zul0QuvUx_QHesVbMsCbMZ1dPj2L991lNAAET_RhVUNPMSVsn2iMcHLJlObw6K3HeLFTNq7c9DNcMxw7Fco1aVFleUNLiaysoNWSQ36XDrZL-REcV3YZp07We5KGDcSwHOPU9lIt6kSm2eWTvuk5Y9nw3sb9xRQo7cqmkvduKotouzygzsPgyVg97dBUno4fy0WQ?access_token=EwAQA61DBAAUmcDj0azQ5tf1lkBfAvHLBzXl5ugAAb0zJ9FE0bs2Q%2bQB9PmQPy1ZOFwiq8OVPwLVWB0LDbTdecSpwIJnEcQQTYmBnDj90m2Ax6ygPl7eIFVl1CCWUXWygIJToqdP5zwdGk0ySFWoXpVwpa9yXh4FEFAaPqVu8Jn3G8rlNJpE0JRl24zKV4ACtjunqXRyRRTqvmd91eQRyfdG0WkX2%2b0lzdCM7QXChYxUMClUfNYvPsDXmaqV4aRO23ZRPC8CtviFIcFKeD0Geugwcxr4Scbdds9lMNmWFiMY%2bPnbFnc05j/ZCjQDjTuFkZ0PqVZgrPwYc2j2mTddAA%2bWihzxaTBDNIbNeFuvHHlV%2bIbBekw6IJ5QBKY3IX0DZgAACAv4r8lI2N574AFM/xjFG1Mg%2bvlJnAPbrOiPXk5/zXcn6yR197e2X/psR8S9suHqwxtuhb3rIvq6oISyCyTymFqFN1SgoP%2bHoECCb0qkZXg5vR1hfPrEdwd2Ohx6oRkdJlr6dvaUccYCDmVCIN8vPGlTXLtE46YYCu77R60WZsmlLhQGV6%2betztpmfU3bF5TnLOpbOrTmwoxamrPtMMj5/rE3NqMqOEgNeyJT66uO1wthEhkdt7dgBQLfscQ0/fOxg2y/1hHOyquRV7aaaHS7z7aRE2%2bkQuovP7gc1J/hbgxLHg%2bojGsYbf0z1UMTD/vi9ZBZKd%2bsDEdIWsKbgYGdw7uf3agRBV4yKLek48TycK4lUk82XFzBb4GZyRV0k3T0G2qk79/ntkzzQlZBCsLp7a/fuxvezmxn3KtJkZezOMbuwGvfht16kW61WGPBy7N4dU2XiZ21qcH4S5Yl6Ug0MQb0M3FJNaL/XIp3C0%2b5T%2bDkQUOvWbDZBhnwhgJIgaWwOYI1VzbJJBWsJSpMwF%2bZSahsQytiVgPduxI/KSymBQhhAVjeZ44RZ8P5LmSOxrZOdGBNLmisgBkmkRkJFWwo/e2U4SJWGOtOAOMo%2bndz3qRzWsu7CbKRZgGxGf0rJWb3Qn7l7DFqRiuBfMNAg%3d%3d
          condition: eq(variables['System.JobName'], 'macos')
        - pwsh: |
            dotnet tool uninstall --global Cake.Tool
            dotnet tool install --global Cake.Tool
            dotnet tool install --global boots
            boots https://public.bl.files.1drv.com/y4mSL0Jrp7m6JsheLUoC5OvtK4Jluwh0y-DNAnWP9blaU44CbPU8uH8i2vNLL5XZPRqEvRe1ZLYxj473I3SR7kGuYuglg-vbtzgKQt2Sib3yuKNSTDJmyEt8ruU8y-LMgI4tkEIQzaWvE3y-MfZvN-pVnVJ9mP2u1uUYP7R1TyrO9U2MzldT0Trkmwe3uy5L1qCEe6qxD2boMAqyagvr0WI7B1EfS6ELJHf2dRSe6tZBUc?access_token=EwAQA61DBAAUmcDj0azQ5tf1lkBfAvHLBzXl5ugAAb0zJ9FE0bs2Q%2bQB9PmQPy1ZOFwiq8OVPwLVWB0LDbTdecSpwIJnEcQQTYmBnDj90m2Ax6ygPl7eIFVl1CCWUXWygIJToqdP5zwdGk0ySFWoXpVwpa9yXh4FEFAaPqVu8Jn3G8rlNJpE0JRl24zKV4ACtjunqXRyRRTqvmd91eQRyfdG0WkX2%2b0lzdCM7QXChYxUMClUfNYvPsDXmaqV4aRO23ZRPC8CtviFIcFKeD0Geugwcxr4Scbdds9lMNmWFiMY%2bPnbFnc05j/ZCjQDjTuFkZ0PqVZgrPwYc2j2mTddAA%2bWihzxaTBDNIbNeFuvHHlV%2bIbBekw6IJ5QBKY3IX0DZgAACAv4r8lI2N574AFM/xjFG1Mg%2bvlJnAPbrOiPXk5/zXcn6yR197e2X/psR8S9suHqwxtuhb3rIvq6oISyCyTymFqFN1SgoP%2bHoECCb0qkZXg5vR1hfPrEdwd2Ohx6oRkdJlr6dvaUccYCDmVCIN8vPGlTXLtE46YYCu77R60WZsmlLhQGV6%2betztpmfU3bF5TnLOpbOrTmwoxamrPtMMj5/rE3NqMqOEgNeyJT66uO1wthEhkdt7dgBQLfscQ0/fOxg2y/1hHOyquRV7aaaHS7z7aRE2%2bkQuovP7gc1J/hbgxLHg%2bojGsYbf0z1UMTD/vi9ZBZKd%2bsDEdIWsKbgYGdw7uf3agRBV4yKLek48TycK4lUk82XFzBb4GZyRV0k3T0G2qk79/ntkzzQlZBCsLp7a/fuxvezmxn3KtJkZezOMbuwGvfht16kW61WGPBy7N4dU2XiZ21qcH4S5Yl6Ug0MQb0M3FJNaL/XIp3C0%2b5T%2bDkQUOvWbDZBhnwhgJIgaWwOYI1VzbJJBWsJSpMwF%2bZSahsQytiVgPduxI/KSymBQhhAVjeZ44RZ8P5LmSOxrZOdGBNLmisgBkmkRkJFWwo/e2U4SJWGOtOAOMo%2bndz3qRzWsu7CbKRZgGxGf0rJWb3Qn7l7DFqRiuBfMNAg%3d%3d
          condition: eq(variables['System.JobName'], 'windows')
      tools:
        - 'xamarin.androidbinderator.tool': '0.4.3'
        - 'xamarin.androidx.migration.tool': '1.0.8'
  - ${{ if eq(variables['System.TeamProject'], 'devdiv') }}:
    - template: sign-artifacts/jobs/v2.yml@internal-templates
      parameters:
        timeoutInMinutes: 120
        dependsOn: [ 'build' ]
